CC = g++
CFLAGS = -Wall -std=c++11

all: tp1 tp2 tp3 tp4 tp5 tp6 tp7 tp8 tp9 tp10 tp11 tp12 tp13 tp14 tp15 tp16 tp17

tp1: tp1.cpp
	$(CC) $(CFLAGS) -o tp1 tp1.cpp

tp2: tp2.cpp
	$(CC) $(CFLAGS) -o tp2 tp2.cpp

tp3: tp3.cpp
	$(CC) $(CFLAGS) -o tp3 tp3.cpp

tp4: tp4.cpp
	$(CC) $(CFLAGS) -o tp4 tp4.cpp

tp5: tp5.cpp
	$(CC) $(CFLAGS) -o tp5 tp5.cpp

tp6: tp6.cpp
	$(CC) $(CFLAGS) -o tp6 tp6.cpp

tp7: tp7.cpp
	$(CC) $(CFLAGS) -o tp7 tp7.cpp

tp8: tp8.cpp
	$(CC) $(CFLAGS) -o tp8 tp8.cpp

tp9: tp9.cpp
	$(CC) $(CFLAGS) -o tp9 tp9.cpp

tp10: tp10.cpp
	$(CC) $(CFLAGS) -o tp10 tp10.cpp

tp11: tp11.cpp
	$(CC) $(CFLAGS) -o tp11 tp11.cpp

tp12: tp12.cpp
	$(CC) $(CFLAGS) -o tp12 tp12.cpp

tp13: tp13.cpp
	$(CC) $(CFLAGS) -o tp13 tp13.cpp

tp14: tp14.cpp
	$(CC) $(CFLAGS) -o tp14 tp14.cpp

tp15: tp15.cpp
	$(CC) $(CFLAGS) -o tp15 tp15.cpp

tp16: tp16.cpp
	$(CC) $(CFLAGS) -o tp16 tp16.cpp

tp17: tp17.cpp
	$(CC) $(CFLAGS) -o tp17 tp17.cpp

run1: tp1
	./tp1

run2: tp2
	./tp2

run3: tp3
	./tp3

run4: tp4
	./tp4

run5: tp5
	./tp5

run6: tp6
	./tp6

run7: tp7
	./tp7

run8: tp8
	./tp8

run9: tp9
	./tp9

run10: tp10
	./tp10

run11: tp11
	./tp11

run12: tp12
	./tp12

run13: tp13
	./tp13

run14: tp14
	./tp14

run15: tp15
	./tp15

run16: tp16
	./tp16

run17: tp17
	./tp17

clean:
	rm -f tp1 tp2 tp3 tp4 tp5 tp6 tp7 tp8 tp9 tp10 tp11 tp12 tp13 tp14 tp15 tp16 tp17